name: plan-terraform
on:
  pull_request:
    branches:
      - main
    paths:
      - 'terraform/**'

env:
  TF_CLOUD_ORGANIZATION: "emeka-homelab"
  TF_API_TOKEN: ${{ secrets.TF_CLOUD_API_TOKEN }}
  TF_WORKSPACE: "default"
  CONFIG_DIRECTORY: "./"
      
jobs:
  plan:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_CLOUD_API_TOKEN }}
      - name: Terraform Init
        run: terraform init -input=false
      - name: Terraform Plan
        run: terraform plan -input=false
     
