name: plan-terraform
on:
  pull_request:
    branches:
      - main
    paths:
      - 'terraform/**'
      
jobs:
  plan:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./terraform    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Terraform Init
        run: terraform init -input=false
      - name: Terraform Plan
        run: terraform plan -input=false
     
